const firebaseConfig={databaseURL:"https://esh7nly-default-rtdb.firebaseio.com/"};
let db=null;try{if(window.firebase){firebase.initializeApp(firebaseConfig);db=firebase.database()}}catch(e){}
const KEY="esh7nly_final_state";
const defaultState={settings:{username:"admin",password:"1234",costs:{10:0,20:0,30:0,40:0,50:0,60:0,70:0}},subscribers:[],activities:[],owaisPayments:[]};
let state=loadState(),currentDay=11,currentMerchant="abd",selected=new Set();
function loadState(){try{const x=JSON.parse(localStorage.getItem(KEY)||"{}");return{...defaultState,...x,settings:{...defaultState.settings,...(x.settings||{}),costs:{...defaultState.settings.costs,...((x.settings||{}).costs||{})}},subscribers:x.subscribers||[],activities:x.activities||[],owaisPayments:x.owaisPayments||[]}}catch(e){return JSON.parse(JSON.stringify(defaultState))}}
function saveLocal(){localStorage.setItem(KEY,JSON.stringify(state))}
function money(n){return Number(n||0).toLocaleString("ar-EG")+" ج"}
function merchantName(v){return v==="abd"?"عبد الحكيم":"أسامة"}
function packageCost(p){return Number(state.settings.costs?.[p]||0)}
function todayISO(){return new Date().toISOString().slice(0,10)}
function addLog(text){state.activities.unshift({text,time:new Date().toLocaleString("ar-EG")});state.activities=state.activities.slice(0,100);saveLocal();renderLog()}
async function syncPush(){saveLocal();if(!db)return;try{await db.ref("esh7nly").set(state);setSync("متزامن")}catch(e){setSync("محلي - تعذر المزامنة")}}
async function syncPull(){if(!db)return;try{const s=await db.ref("esh7nly").once("value");if(s.exists()){const x=s.val();state={...defaultState,...x,settings:{...defaultState.settings,...(x.settings||{}),costs:{...defaultState.settings.costs,...((x.settings||{}).costs||{})}},subscribers:x.subscribers||[],activities:x.activities||[],owaisPayments:x.owaisPayments||[]};saveLocal();renderAll()}setSync("متزامن")}catch(e){setSync("محلي")}}
function setSync(t){const a=document.getElementById("syncMini"),b=document.getElementById("syncStatus");if(a)a.textContent=t;if(b)b.textContent=t}
function isLogged(){return sessionStorage.getItem("esh7nly_logged")==="1"}
function login(){const u=document.getElementById("loginUser").value.trim(),p=document.getElementById("loginPass").value;if(u===state.settings.username&&p===state.settings.password){sessionStorage.setItem("esh7nly_logged","1");showApp();document.getElementById("loginMsg").textContent=""}else document.getElementById("loginMsg").textContent="اسم المستخدم أو كلمة المرور غير صحيحة"}
function showApp(){document.getElementById("login").classList.add("hidden");document.getElementById("app").classList.remove("hidden");renderAll();syncPull()}
function nav(id){document.querySelectorAll(".page").forEach(x=>x.classList.add("hidden"));document.getElementById(id).classList.remove("hidden");document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===id));renderAll()}
function subscribers(){return state.subscribers||[]}
function dayStats(day){const a=subscribers().filter(s=>Number(s.day)===Number(day));const sales=a.reduce((x,s)=>x+Number(s.price||0),0);const cost=a.reduce((x,s)=>x+packageCost(s.package),0);const unpaidO=a.filter(s=>s.owais&&!s.paid).reduce((x,s)=>x+Number(s.price||0),0);return{all:a,sales,cost,profit:sales-cost,owaisDue:unpaidO}}
function totals(){const a=subscribers();const sales=a.reduce((x,s)=>x+Number(s.price||0),0),cost=a.reduce((x,s)=>x+packageCost(s.package),0);return{count:a.length,sales,cost,profit:sales-cost,owaisDue:a.filter(s=>s.owais&&!s.paid).reduce((x,s)=>x+Number(s.price||0),0),unpaid:a.filter(s=>!s.paid).reduce((x,s)=>x+Number(s.price||0),0)}}
function renderAll(){renderHome();renderSubscribers();renderMerchants();renderDashboard();renderLog()}
function renderHome(){const t=totals(),d11=dayStats(11),d26=dayStats(26);document.getElementById("homeStats").innerHTML=`<div class="stat"><span>إجمالي التفعيلات</span><b>${t.count}</b></div><div class="stat"><span>إجمالي المبيعات</span><b>${money(t.sales)}</b></div><div class="stat"><span>إجمالي الربح</span><b class="profit">${money(t.profit)}</b></div><div class="stat"><span>حساب عويس</span><b class="danger">${money(t.owaisDue)}</b></div>`;document.getElementById("dayProfitCards").innerHTML=[{d:11,s:d11},{d:26,s:d26}].map(x=>`<div class="stat"><span>تفعيلات يوم ${x.d}</span><b>${x.s.all.length}</b><div class="date-note">مبيعات ${money(x.s.sales)} · تكلفة ${money(x.s.cost)}</div><div class="profit">ربح ${money(x.s.profit)}</div></div>`).join("");renderAlerts(false)}
function renewalClass(date){if(!date)return"green";const diff=Math.ceil((new Date(date+"T23:59:59")-new Date())/86400000);return diff<0?"red":diff<=2?"red":diff<=5?"yellow":"green"}
function renderAlerts(all=false){const arr=subscribers().filter(s=>s.dueDate).sort((a,b)=>String(a.dueDate).localeCompare(String(b.dueDate))).filter(s=>{const diff=Math.ceil((new Date(s.dueDate+"T23:59:59")-new Date())/86400000);return all||diff<=5}).slice(0,all?50:6);const box=document.getElementById("renewalAlerts");if(!arr.length){box.innerHTML='<div class="alert green">لا توجد تجديدات قريبة 🎉</div>';return}box.innerHTML=arr.map(s=>`<div class="alert ${renewalClass(s.dueDate)}"><div class="row"><div><b>${esc(s.name)}</b><div>${esc(s.number)} · ${merchantName(s.merchant)}</div><div class="date-note">الاستحقاق: ${s.dueDate}</div></div><div class="mini-actions"><button onclick="editSubscriber('${s.id}')">تعديل</button>${s.whatsapp?`<button class="whatsapp" onclick="window.open('${safeUrl(s.whatsapp)}','_blank')">واتساب</button>`:""}</div></div></div>`).join("")}
function renderSubscribers(){const d=dayStats(currentDay),search=(document.getElementById("search")?.value||"").trim().toLowerCase(),status=document.getElementById("statusFilter")?.value||"all",mf=document.getElementById("merchantFilter")?.value||"all",pf=document.getElementById("packageFilter")?.value||"all";document.querySelectorAll(".day").forEach(b=>b.classList.toggle("active",Number(b.dataset.day)===currentDay));document.getElementById("subscriberSummary").innerHTML=`<div class="box"><span>العدد</span><b>${d.all.length}</b></div><div class="box"><span>المبيعات</span><b>${money(d.sales)}</b></div><div class="box"><span>التكلفة</span><b>${money(d.cost)}</b></div><div class="box"><span>الربح</span><b class="profit">${money(d.profit)}</b></div>`;const list=d.all.filter(s=>{const q=(s.name+" "+s.number+" "+(s.contact||"")).toLowerCase();return(!search||q.includes(search))&&(status==="all"||(status==="paid"?s.paid:!s.paid))&&(mf==="all"||s.merchant===mf)&&(pf==="all"||String(s.package)===pf)});document.getElementById("subscriberList").innerHTML=list.length?list.map(card).join(""):'<div class="alert">لا توجد نتائج.</div>'}
function card(s){const cost=packageCost(s.package),profit=Number(s.price||0)-cost;return `<div class="subscriber-card"><div class="row"><div><input type="checkbox" class="pick" data-id="${s.id}" ${selected.has(s.id)?"checked":""}> <b>${esc(s.name)}</b></div><span class="chip ${s.paid?"paid":"unpaid"}">${s.paid?"مسدد":"غير مسدد"}</span></div><div class="chips"><span class="chip">${esc(s.number)}</span><span class="chip">باقة ${s.package}</span><span class="chip">${merchantName(s.merchant)}</span>${s.owais?'<span class="chip">عويس</span>':""}<span class="chip profit">ربح ${money(profit)}</span></div><div class="date-note">سعر البيع: ${money(s.price)} · التكلفة: ${money(cost)}${s.dueDate?" · الاستحقاق: "+s.dueDate:""}</div>${s.notes?`<div class="date-note">📝 ${esc(s.notes)}</div>`:""}<div class="card-actions"><button onclick="editSubscriber('${s.id}')">تعديل</button><button onclick="togglePaid('${s.id}')">${s.paid?"إلغاء التسديد":"تسديد"}</button>${s.whatsapp?`<button class="whatsapp" onclick="window.open('${safeUrl(s.whatsapp)}','_blank')">واتساب</button>`:""}<button onclick="deleteSubscriber('${s.id}')">حذف</button></div></div>`}
function renderMerchants(){const a=subscribers().filter(s=>s.merchant===currentMerchant),sales=a.reduce((x,s)=>x+Number(s.price||0),0),cost=a.reduce((x,s)=>x+packageCost(s.package),0);document.querySelectorAll(".merchant-tab").forEach(b=>b.classList.toggle("active",b.dataset.merchant===currentMerchant));document.getElementById("merchantSummary").innerHTML=`<div class="box"><span>الأرقام</span><b>${a.length}</b></div><div class="box"><span>المبيعات</span><b>${money(sales)}</b></div><div class="box"><span>التكلفة</span><b>${money(cost)}</b></div><div class="box"><span>الربح</span><b class="profit">${money(sales-cost)}</b></div>`;document.getElementById("merchantList").innerHTML=a.length?a.map(s=>`<div class="merchant-card"><div class="row"><b>${esc(s.name)}</b><span>${esc(s.number)}</span></div><div class="date-note">يوم ${s.day} · باقة ${s.package} · بيع ${money(s.price)} · تكلفة ${money(packageCost(s.package))} · <span class="profit">ربح ${money(Number(s.price)-packageCost(s.package))}</span></div></div>`).join(""):'<div class="alert">لا توجد أرقام لهذا التاجر.</div>'}
function renderDashboard(){const t=totals();document.getElementById("reportStats").innerHTML=`<div class="stat"><span>المبيعات</span><b>${money(t.sales)}</b></div><div class="stat"><span>التكلفة</span><b>${money(t.cost)}</b></div><div class="stat"><span>الربح</span><b class="profit">${money(t.profit)}</b></div><div class="stat"><span>غير مسدد</span><b class="danger">${money(t.unpaid)}</b></div>`;document.getElementById("costInputs").innerHTML=[10,20,30,40,50,60,70].map(p=>`<label>باقة ${p}<input data-cost="${p}" type="number" min="0" value="${packageCost(p)}"></label>`).join("");document.getElementById("settingUser").value=state.settings.username;document.getElementById("settingPass").value=state.settings.password;const d11=dayStats(11),d26=dayStats(26),all=t.owaisDue;document.getElementById("owaisAccount").innerHTML=`<div class="box"><span>يوم 11</span><b>${money(d11.owaisDue)}</b></div><div class="box"><span>يوم 26</span><b>${money(d26.owaisDue)}</b></div><div class="box"><span>الإجمالي</span><b class="danger">${money(all)}</b></div>`}
function renderLog(){const el=document.getElementById("activityLog");if(el)el.innerHTML=(state.activities||[]).slice(0,40).map(x=>`<div class="log-item"><b>${esc(x.text)}</b><div class="date-note">${x.time}</div></div>`).join("")||'<div class="muted">لا توجد عمليات بعد.</div>'}
function openModal(id=null){const s=id?subscribers().find(x=>x.id===id):null;document.getElementById("modal").classList.remove("hidden");document.getElementById("modalTitle").textContent=s?"تعديل التفعيل":"تفعيل جديد";document.getElementById("editId").value=s?.id||"";document.getElementById("fName").value=s?.name||"";document.getElementById("fNumber").value=s?.number||"";document.getElementById("fContact").value=s?.contact||"";document.getElementById("fWhatsapp").value=s?.whatsapp||"";document.getElementById("fPackage").value=s?.package||"10";document.getElementById("fPrice").value=s?.price||"";document.getElementById("fPassword").value=s?.password||"";document.getElementById("fNotes").value=s?.notes||"";document.getElementById("fDueDate").value=s?.dueDate||"";document.getElementById("fMerchant").value=s?.merchant||"abd";document.getElementById("fOwais").checked=!!s?.owais;checkCost()}
function closeModal(){document.getElementById("modal").classList.add("hidden")}
function editSubscriber(id){openModal(id)}
function uid(){return (crypto&&crypto.randomUUID)?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function saveSubscriber(e){e.preventDefault();const id=document.getElementById("editId").value||uid();const p=Number(document.getElementById("fPackage").value),price=Number(document.getElementById("fPrice").value||0),old=subscribers().find(s=>s.id===id);const s={id,name:document.getElementById("fName").value.trim(),number:document.getElementById("fNumber").value.trim(),contact:document.getElementById("fContact").value.trim(),whatsapp:document.getElementById("fWhatsapp").value.trim(),package:p,price,password:document.getElementById("fPassword").value,notes:document.getElementById("fNotes").value.trim(),dueDate:document.getElementById("fDueDate").value,merchant:document.getElementById("fMerchant").value,owais:document.getElementById("fOwais").checked,day:old?.day||currentDay,paid:old?.paid||false,createdAt:old?.createdAt||new Date().toISOString()};const duplicate=subscribers().some(x=>x.number===s.number&&x.id!==id&&Number(x.day)===s.day);if(duplicate&&!confirm("الرقم موجود بالفعل في نفس يوم التفعيل. هل تريد المتابعة؟"))return;if(price<packageCost(p)&&!confirm("سعر البيع أقل من التكلفة. هل تريد المتابعة؟"))return;const i=subscribers().findIndex(x=>x.id===id);if(i>=0)state.subscribers[i]=s;else state.subscribers.push(s);addLog((old?"تعديل":"إضافة")+" المشترك "+s.name+" - "+s.number);closeModal();selected.delete(id);syncPush();renderAll()}
function togglePaid(id){const s=subscribers().find(x=>x.id===id);if(!s)return;s.paid=!s.paid;addLog((s.paid?"تسديد ":"إلغاء تسديد ")+s.name);syncPush();renderAll()}
function deleteSubscriber(id){const s=subscribers().find(x=>x.id===id);if(!s)return;if(confirm("حذف المشترك؟")){state.subscribers=state.subscribers.filter(x=>x.id!==id);addLog("حذف المشترك "+s.name);syncPush();renderAll()}}
function paySelected(){const ids=[...selected];if(!ids.length)return alert("حدد أرقام أولاً");ids.forEach(id=>{const s=subscribers().find(x=>x.id===id);if(s)s.paid=true});addLog("تسديد "+ids.length+" مشترك");selected.clear();syncPush();renderAll()}
function payOwais(){const a=dayStats(currentDay).all.filter(s=>s.owais&&!s.paid);if(!a.length)return alert("لا يوجد مبلغ مستحق لعويس في هذا اليوم");const total=a.reduce((x,s)=>x+Number(s.price||0),0);if(confirm("تسديد حساب عويس بمبلغ "+money(total)+"؟")){a.forEach(s=>s.paid=true);state.owaisPayments.push({day:currentDay,amount:total,time:new Date().toISOString()});addLog("تسديد حساب عويس يوم "+currentDay+" بمبلغ "+money(total));syncPush();renderAll()}}
function payOwaisAll(){const a=subscribers().filter(s=>s.owais&&!s.paid);if(!a.length)return alert("لا يوجد حساب مستحق");const total=a.reduce((x,s)=>x+Number(s.price||0),0);if(confirm("تسديد كامل حساب عويس "+money(total)+"؟")){a.forEach(s=>s.paid=true);state.owaisPayments.push({day:"all",amount:total,time:new Date().toISOString()});addLog("تسديد كامل حساب عويس "+money(total));syncPush();renderAll()}}
function checkCost(){const p=Number(document.getElementById("fPackage").value),price=Number(document.getElementById("fPrice").value||0),box=document.getElementById("costWarning");if(price>0&&price<packageCost(p)){box.textContent="تنبيه: سعر البيع أقل من تكلفة الشراء ("+money(packageCost(p))+").";box.classList.remove("hidden")}else box.classList.add("hidden")}
function saveCosts(){document.querySelectorAll("[data-cost]").forEach(i=>state.settings.costs[i.dataset.cost]=Number(i.value||0));addLog("تحديث تكاليف الباقات");syncPush();renderAll()}
function saveLogin(){state.settings.username=document.getElementById("settingUser").value.trim()||"admin";state.settings.password=document.getElementById("settingPass").value||"1234";saveLocal();addLog("تحديث بيانات الدخول");alert("تم حفظ بيانات الدخول")}
function exportBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="esh7nly-backup-"+todayISO()+".json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function importBackup(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.subscribers||!x.settings)throw Error();state=x;saveLocal();addLog("استيراد نسخة احتياطية");syncPush();renderAll();alert("تم الاستيراد")}catch(err){alert("ملف غير صالح")}};r.readAsText(f)}
function safeUrl(u){try{const x=new URL(u);return /^https?:$/.test(x.protocol)?x.href:"#"}catch(e){return"#"}}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
document.addEventListener("click",e=>{const p=e.target.closest("[data-page]");if(p)nav(p.dataset.page);if(e.target.matches(".day")){currentDay=Number(e.target.dataset.day);selected.clear();renderSubscribers()}if(e.target.matches(".merchant-tab")){currentMerchant=e.target.dataset.merchant;renderMerchants()}});
document.getElementById("loginBtn").onclick=login;document.getElementById("loginPass").addEventListener("keydown",e=>{if(e.key==="Enter")login()});document.getElementById("logoutBtn").onclick=()=>{sessionStorage.removeItem("esh7nly_logged");location.reload()};document.getElementById("quickAdd").onclick=()=>openModal();document.getElementById("addSubscriberBtn").onclick=()=>openModal();document.getElementById("closeModal").onclick=closeModal;document.getElementById("modal").addEventListener("click",e=>{if(e.target.id==="modal")closeModal()});document.getElementById("subscriberForm").onsubmit=saveSubscriber;document.getElementById("fPackage").onchange=checkCost;document.getElementById("fPrice").oninput=checkCost;document.getElementById("paySelectedBtn").onclick=paySelected;document.getElementById("payOwaisBtn").onclick=payOwais;document.getElementById("payOwaisAllBtn").onclick=payOwaisAll;document.getElementById("saveCostsBtn").onclick=saveCosts;document.getElementById("saveLoginBtn").onclick=saveLogin;document.getElementById("exportBtn").onclick=exportBackup;document.getElementById("importFile").onchange=importBackup;document.getElementById("forceSyncBtn").onclick=syncPush;document.getElementById("showAlertsBtn").onclick=()=>{nav("homePage");renderAlerts(true)};["search","statusFilter","merchantFilter","packageFilter"].forEach(id=>document.getElementById(id).addEventListener("input",renderSubscribers));document.getElementById("selectAllBtn").onclick=()=>{const boxes=[...document.querySelectorAll(".pick")];const allChecked=boxes.length&&boxes.every(c=>c.checked);boxes.forEach(c=>{c.checked=!allChecked;c.checked?selected.add(c.dataset.id):selected.delete(c.dataset.id)})};document.addEventListener("change",e=>{if(e.target.matches(".pick")){e.target.checked?selected.add(e.target.dataset.id):selected.delete(e.target.dataset.id)}});
if(isLogged())showApp();else document.getElementById("login").classList.remove("hidden");
